os:
  - linux
language: php
php:
  - '7.2'
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - phpenv rehash
  - nvm install 8.12.0
  - npm install npm@latest -g
  - npm install
script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
notifications:
  email:
    - reginaldo.junior696@gmail.com